name Deploy Pelican site to GitHub Pages

on
  push
    branches
      - main

jobs
  build
    runs-on ubuntu-latest

    steps
    - name Checkout repository
      uses actionscheckout@v4.2.2

    - name Set up Python
      uses actionssetup-python@v5.4.0
      with
        python-version '3.11.4'

    - name Install dependencies
      run 
        python -m pip install --upgrade pip
        pip install pelican markdown

    - name Build site
      run pelican content -s pelicanconf.py

    - name Deploy to GitHub Pages
      uses peaceirisactions-gh-pages@v3
      with
        github_token ${{ secrets.GITHUB_TOKEN }}
        publish_dir .output
        publish_branch gh-pages
        allow_empty_commit false
        keep_files false
        force_orphan false
        enable_jekyll false
        disable_nojekyll false
        exclude_assets .github
