name: Deploy Pelican site to GitHub Pages

on:
  push:
    branches:
      - main  # Триггер на изменения в ветке main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2  # Клонируем репозиторий

    - name: Set up Python
      uses: actions/setup-python@v5.4.0  # Устанавливаем Python
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican markdown  # Устанавливаем Pelican и Markdown

    - name: Build site
      run: pelican content -s pelicanconf.py  # Собираем сайт

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Деплоим на GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к репозиторию
        publish_dir: ./output  # Папка с собранным сайтом