name: Deploy Pelican site to GitHub Pages

on:
  push:
    branches:
      - main  # Триггер на изменения в ветке main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2  # Клонируем репозиторий

    - name: Set up Python
      uses: actions/setup-python@v5.4.0  # Устанавливаем Python
name: Deploy Pelican site to GitHub Pages

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican markdown

    - name: Build site
      run: pelican content -s pelicanconf.py

    - name: List output directory
      run: ls -R ./output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        allow_empty_commit: false
        keep_files: false
        force_orphan: false
        enable_jekyll: false
        disable_nojekyll: false
        exclude_assets: .github